name: query

on:
  workflow_dispatch:
    inputs:
      url:
        type: text
        description: 'URL'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        run: |
          curl -vvv "${{ inputs.url }}"
