name: query

on:
  workflow_dispatch:
    inputs:
      url:
        type: text
        description: 'URL'
      method:
        type: text
        description: 'Method'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ inputs.url }}"
          method: GET
          preventFailureOnNoResponse: true
          ignoreStatusCodes: '403'
        id: myRequest
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
          echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
