name: query

on:
  workflow_dispatch:
    inputs:
      url:
        type: text
        description: 'URL'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: indiesdev/curl@v1.1
        with:
          log-response: true
          url: "${{ inputs.url }}"
